version: '3.8'
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testlocal
    networks:
      - default

  web:
    build: .
    environment:
      - DB_NAME=testlocal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "1338:1338"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:1338"
    depends_on:
      - db
    networks:
      - default

volumes:
  postgres_data:

networks:
    default:
